### ISSUE TITLE
Idempotency: SECTION6 | 6.1.4.1 breaks AIDE

### ISSUE THREAD

**Issue by egorksv** [MVladislav/ansible-cis-ubuntu-2404#12]
### Describe the problem

6.1.4.1 implementation changes ownership of everything under /var/log to root.

After that, AIDE fails to start due to /var/log/aide.log being root-owned:

```
Feb 22 13:20:22 webserver systemd[1]: Starting dailyaidecheck.service - daily AIDE check...
Feb 22 13:25:30 webserver dailyaidecheck[62532]: ln: failed to create hard link '/var/log/aide//aide.log.0' => '/var/log/aide/aide.log': Operation not permitted
Feb 22 13:25:30 webserver dailyaidecheck[62519]: Error hardlinking /var/log/aide/aide.log to /var/log/aide//aide.log.0
```

### Expected behavior

/var/log/aide and all files under it to be owned by _aide user

### What is version of application which has the issue?

git latest

### What type of installation are you running?

OS (setup.py)

### What type of device you use to interact with the application?

OS: [e.g. linux, windows, ios]

### Example JSON snippet

```json

```

### Anything in the logs that might be useful for us?

```txt

```

**Comment by MVladislav** [comment]
Hi @egorksv 

Could you confirm whether this role was run on a fresh installation or an existing one? 
The task for `6.1.4.1` is executed before **AIDE** ( >= `6.3.1`) is set up, 
which means the `/var/log/aide` directory doesn’t exist at the time of execution. 

I will review and improve the logic to handle both cases - where the directory exists or doesn’t exist - so that it correctly sets the ownership for both scenarios.

As a quick workaround, you can update the value for `cis_ubuntu2404_logfiles_access` as follows:

> Please note, I have not verified if the `mode`, `owner` and `group` are correct in the example below.

```
cis_ubuntu2404_logfiles_access:
  - files: 'lastlog|lastlog\.*|wtmp|wtmp\.*|wtmp-*|btmp|btmp\.*|btmp-*|README'
    mode: "0664"
    owner: root
    group: utmp # root|utmp
  - files: 'secure|auth\.log|syslog|messages'
    mode: "0640"
    owner: syslog # root|syslog
    group: "{{ cis_ubuntu2404_audit_log_group }}" # root|adm
  - files: "SSSD|sssd"
    mode: "0660"
    owner: sssd # root|sssd
    group: sssd # root|sssd
  - files: "gdm|gdm3"
    mode: "0660"
    owner: root
    group: gdm # root|gdm|gdm3
  - files: '*\.journal|*\.journal~'
    mode: "0640"
    owner: root
    group: systemd-journal # root|systemd-journal

  - files: 'aide|aide\.log*'
    mode: "0640"
    owner: _aide
    group: _aide
```
