### ISSUE TITLE
Error executing apparmor

### ISSUE THREAD

**Issue by DrCapricorn** [MVladislav/ansible-cis-ubuntu-2404#8]
### Describe the problem

First of all: thank you very much for making this available. While running the sec-short playbook on Ubuntu Server 24.04.01 LTS (version now available to download) I ran into this problem:

```
[started TASK: ansible-cis-ubuntu-2404 : SECTION1 | 1.3.1.3 | Ensure all AppArmor Profiles are in enforce or complain mode on server]
fatal: [server]: FAILED! => changed=false 
  cmd:
  - /usr/sbin/aa-complain
  - /etc/apparmor.d/*
  delta: '0:00:00.542372'
  end: '2025-01-05 13:06:23.301155'
  msg: non-zero return code
  rc: 1
  start: '2025-01-05 13:06:22.758783'
  stderr: |-
    Traceback (most recent call last):
      File "/usr/sbin/aa-complain", line 33, in <module>
        tool.cmd_complain()
      File "/usr/lib/python3/dist-packages/apparmor/tools.py", line 140, in cmd_complain
        for (program, prof_filename, output_name) in self.get_next_for_modechange():
      File "/usr/lib/python3/dist-packages/apparmor/tools.py", line 97, in get_next_for_modechange
        aaui.UI_Info(_('Profile for %s not found, skipping') % output_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: 'NoneType' object is not callable
  
  
    An unexpected error occurred!
  
    For details, see /tmp/apparmor-bugreport-5ym4u7tp.txt
    Please consider reporting a bug at https://gitlab.com/apparmor/apparmor/-/issues
    and attach this file.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
The bugreport in question:

[apparmor-bugreport-5ym4u7tp.txt](https://github.com/user-attachments/files/18310183/apparmor-bugreport-5ym4u7tp.txt)

I hope you can figure out what's wrong. I tried a couple of hours yesterday but I cannot get around it. 

### Expected behavior

Playbook running as expected.

### What is version of application which has the issue?

git

### What type of installation are you running?

OS (setup.py)

### What type of device you use to interact with the application?

OS: [e.g. linux, windows, ios]

**Comment by Luiggi33** [comment]
Hey, are you sure you have the newest version of this role installed? I had the same issue (https://github.com/MVladislav/ansible-cis-ubuntu-2404/issues/4) and the creator of this fixed it in https://github.com/MVladislav/ansible-cis-ubuntu-2404/commit/54038b7de8b1bfbbf3c1f2bb709471086df48283, which helped with my issue

**Comment by DrCapricorn** [comment]
Thank you for the quick response. I did a git clone from your site. Should I download it from somewhere else please?
Git is not my thing and I'm an Ansible Novice so this is all rather new for me.

**Comment by Luiggi33** [comment]
Hm okay if it was a recent clone, it should have everything. It seems this is another issue that I cant help you with right now

**Comment by MVladislav** [comment]
Could you please double-check if you have the latest version by opening the file under `tasks/section1.yml` 
and checking the line with the name `SECTION1 | 1.3.1.3 | Ensure all AppArmor Profiles are in enforce or complain mode`?

_Note: From the logs you provided, it does not look like you have cloned the latest version._
Please confirm if it looks like the following for you (it should start at line `621`):

```yaml
- name: "SECTION1 | 1.3.1.3 | Ensure all AppArmor Profiles are in enforce or complain mode"
  when:
    - cis_ubuntu2404_rule_1_3_1_3
  tags:
    - rule_1_3_1
    - server_l1
    - workstation_l1
  block:
    - name: "SECTION1 | 1.3.1.3 | Ensure all AppArmor Profiles are in enforce or complain mode | get status"
      ansible.builtin.command: "/usr/sbin/apparmor_status --json"
      changed_when: false
      register: cis_ubuntu2404_apparmor_json_status
    - name: "SECTION1 | 1.3.1.3 | Ensure all AppArmor Profiles are in enforce or complain mode | get unconfined profiles"
      ansible.builtin.set_fact:
        cis_ubuntu2404_apparmor_update_to_complain_profiles: "{{ (cis_ubuntu2404_apparmor_json_status.stdout | from_json).profiles | dict2items | selectattr('value', 'in', ['unconfined']) | map(attribute='key') | list }}"
      when: cis_ubuntu2404_apparmor_update_to_complain_profiles is not defined
    - name: "SECTION1 | 1.3.1.3 | Ensure all AppArmor Profiles are in enforce or complain mode | apply unconfined into complain"
      ansible.builtin.command: "/usr/sbin/aa-complain {{ item }}"
      changed_when: false
      failed_when: false # NOTE: this should be later removed when bug for AppArmor is fixed
      loop: "{{ cis_ubuntu2404_apparmor_update_to_complain_profiles }}"
      notify: Restart apparmor
```

> I did a git clone from your site. Should I download it from somewhere else please?

In general only a normal clone like:

```sh
git clone https://github.com/MVladislav/ansible-cis-ubuntu-2404.git
```
